# sudo docker run -d --rm --name mongo -p 27017:27017 -v mongodbdata:/data/db mongo

version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017" # Port mapping should use quotes around the host and container ports
    volumes:
      - mongodbdata:/data/db # Correct mapping syntax for volumes

volumes:
  mongodbdata: # Define named volume outside the services section
